### ISSUE TITLE
[Treantjs]: Is this plugin actively supported?

### ISSUE THREAD

**Issue by egor-progger** [egor-progger/pointlinejs#120]
### Description from treantjs issue

> I see most of the issues are open, can we rely on this plugin? If its supported, may i know example integration for basic crud nodes?

### Treantjs issue link

https://github.com/fperucic/treant-js/issues/150

- [x] add create nodes button (#55)
Example - https://egor-progger.github.io/pointlinejs/examples/action-buttons/

- [x] add update nodes button (#173)
Example - https://egor-progger.github.io/pointlinejs/examples/update-example/

- [x] add delete nodes button (#184)
Example - https://egor-progger.github.io/pointlinejs/examples/remove-example/
